kind: Namespace
apiVersion: v1  
metadata:
  name: {{ include "cluster-landing-zone.namespace" . }}
  annotations:
    code: "{{ .Values.project.code }}"
    environment: "{{ .Values.environment }}"
  labels:
    app.kubernetes.io/managed-by: argocd
