kind: Namespace
apiVersion: v1  
metadata:
  name: {{ .Values.namespace.name }}
  annotations:
    code: "{{ .Values.project.code }}"
    fourc-id: "{{ .Values.project.fourcId }}"
    environment: "{{ .Values.environment }}"
  labels:
    app.kubernetes.io/managed-by: argocd
