kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: contributor-role
  namespace: {{ include "cluster-landing-zone.namespace" . }}
rules: 
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]